vaadin.launch-browser: true
spring.application.name: killrvideo-migration

astra:
  api:
    application-token: ${ASTRA_DB_APPLICATION_TOKEN}
    database-endpoint: ${DB_API_ENDPOINT}
    # not mandatory for data API
    database-id: ${ASTRA_DB_ID}
    database-region: ${ASTRA_DB_REGION}
    cross-region-failback: false
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace: ${ASTRA_DB_KEYSPACE}
        request:
          timeout: 8s
          consistency: LOCAL_QUORUM
          page-size: 5000
      advanced:
        connection:
          init-query-timeout: 10s
          set-keyspace-timeout: 10s
        control-connection:
          timeout: 10s